version: '3.7'

services:
    back:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
            DB_HOST: mongodb
            DB_PORT: 27017
            DB_USER: admin
            DB_PASSWORD: 123456
            DB_DATABASE: school
        depends_on:
            - db
    db:
      
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
